config/routes.rb
Rails.application.routes.draw do
  
  # Homepage
  root 'pages#home'
  
  # User Sessions and Sign Up Page
  get '/signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # Articles, Users, Categories
  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: { minimum: 2, maximum: 50 }
  validates :country, presence: true, length: { minimum: 2, maximum: 10 }
  validates :divesite, length: { minimum: 2, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was created successfully."
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was updated successfully."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @article.destroy
    flash[:success] = "Article was deleted successfully."
    redirect_to articles_path
  end
  
  private
  
    def article_params
      params.require(:article).permit(:title, :country, :divesite, :description, category_ids: [])
    end
    
    def set_article
      @article = Article.find(params[:id])
    end
    
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles."
        redirect_to root_path
      end
    end
  
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        
        <div class="article-title text-center">
          <%= link_to article.title, article_path(article) %>
        </div>
        
        <div class="article-body text-left">
          <strong>Country: </strong><%= article.country %><br/>
          <strong>Dive Site(s): </strong><%= article.divesite %><br/>
          <strong>Created by: </strong><%= article.user.username if article.user %> 
            <%= time_ago_in_words(article.created_at) %> ago, last updated 
            <%= time_ago_in_words(article.updated_at) %> ago<br/>
          <% if article.categories.any? %>
            <strong>Categories: </strong><%= render article.categories %>
          <% end %>
        </div>
        
        <div class="article-body text-center">
          <strong>My Experience</strong><br/><%= truncate(article.description, length: 100) %>
        </div>
        
        <!--Action Buttons-->
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="text-right">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-warning" %> |
            <%= link_to "Delete this article", article_path(article), method: :delete, 
                                                data: { confirm: "Are you sure you want to delete this article?" }, 
                                                class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
      <!--title-->
      <div class="form-group">
        <div class="control-label col-sm-2 text-right">
          <%= f.label :title, "Title" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      
      <!--country-->
      <div class="form-group">
        <div class="control-label col-sm-2 text-right">
          <%= f.label :country, "Country" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :country, class: "form-control", placeholder: "Country where you dived", autofocus: true %>
        </div>
      </div>
      
      <!--divesite-->
      <div class="form-group">
        <div class="control-label col-sm-2 text-right">
          <%= f.label :divesite, "Dive Site" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :divesite, class: "form-control", placeholder: "Name of the dive site or region", autofocus: true %>
        </div>
      </div>
      
      <!--description-->
      <div class="form-group">
        <div class="control-label col-sm-2 text-right">
          <%= f.label :description, "Description" %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Write your story here", autofocus: true %>
        </div>
      </div>
      
      <!--Categories-->
      <div class="form-group">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2"> 
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      
      <!--submit button-->
      <div class="form-group text-center">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit class: 'btn btn-success btn-lg' %>
        </div>
      </div>
      
    <% end %>
    <div class="col-sm-4">
      <%= link_to "Back to Articles Listing", articles_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <h1 class="text-center">Edit Article</h1>
</div>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center">Discover Experiences</h1>

<div class="text-center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>
      
<div class="text-center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <h1 class="text-center">Create Article</h1>
</div>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  
  <!--Profile Picture-->
  <% if @article.user %>
    <ul class="listing">
      <div class="row text-center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by:</li><br/>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  
  <!--Country-->
  <h4 class="show-article-h4"><strong>Country:</strong></h4>
  <%= simple_format(@article.country) %>
  <hr>
  
  <!--Dive Sites-->
  <h4 class="show-article-h4"><strong>Dive Site or Region:</strong></h4>
  <%= simple_format(@article.divesite) %>
  <hr>
  
  <!--Categories-->
  <% if @article.categories.any? %>
    <h4 class="show-article-h4"><strong>Categories:</strong></h4>
    <%= render @article.categories %>
    <hr>
  <% end %>
  
  <!--Experience-->
  <h4 class="show-article-h4"><strong>Experience:</strong></h4>
  <%= simple_format(@article.description) %>
  <hr>
  
  <!--Action Buttons-->
  <div>
    <%= link_to "Back to articles listing", articles_path, class: "btn btn-md btn-primary" %> 
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      | <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-md btn-warning" %> 
      | <%= link_to "Delete this article", article_path(@article), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete this article?" }, 
                                          class: "btn btn-md btn-danger" %>
    <% end %>
  </div>
  
</div>