config/routes.rb
Rails.application.routes.draw do
  
  # Homepage
  root 'pages#home'
  
  # User Sessions and Sign Up Page
  get '/signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # Articles, Users, Categories
  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates_uniqueness_of :name
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :set_category, only: [:edit, :update, :show]
  before_action :require_admin, except: [:index, :show]
  
  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully."
      redirect_to categories_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @category.update(category_params)
      flash[:success] = "Category was updated successfully."
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end
  
  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  private
    
    def category_params
      params.require(:category).permit(:name)
    end
    
    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin?)
        flash[:danger] = "Only admins can perform that action."
        redirect_to categories_path
      end
    end
    
    def set_category
      @category = Category.find(params[:id])
    end
  
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span> &nbsp;

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>

  <!--Name-->
  <div class="form-group">
    <div class="control-label col-sm-3 text-right">
      <%= f.label :name, "Name" %>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", placeholder: "ie. Altitude Diving", autofocus: true %>
    </div>
  </div>

  <br/><br/>
  
  <!--Submit Button-->
  <div class="form-group text-center">
    <div class="col-sm-6 col-sm-offset-3">
      <%= f.submit "Create", class: 'btn btn-success btn-lg' %>
    </div>
  </div>
  
<% end %>
<div class="col-sm-4">
  <%= link_to "Back to Articles Listing", articles_path, class: "btn btn-primary" %>
</div>

app/views/categories/edit.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <h1 class="text-center" id="signup-h1">Edit Category</h1>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center">All Categories</h1>
<div class="text-center">
  <%= will_paginate %>
  
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="text-center well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li>
            <%= pluralize(category.articles.count, "article") %>
          </li>
          <% if logged_in? and current_user.admin? %>
            <br/>
            <li>
              <div class="text-center">
                <%= link_to "Edit this category", edit_category_path(category), class: "btn btn-xs btn-warning" %>
              </div>
            </li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <h1 class="text-center" id="signup-h1">Create Category</h1>
</div>

<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>

  <!--Name-->
  <div class="form-group">
    <div class="control-label col-sm-3 text-right">
      <%= f.label :name, "Name" %>
    </div>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", placeholder: "ie. Altitude Diving", autofocus: true %>
    </div>
  </div>

  <br/><br/>
  
  <!--Submit Button-->
  <div class="form-group text-center">
    <div class="col-sm-6 col-sm-offset-3">
      <%= f.submit "Create", class: 'btn btn-success btn-lg' %>
    </div>
  </div>
  
<% end %>
<div class="col-sm-4">
  <%= link_to "Back to Articles Listing", articles_path, class: "btn btn-primary" %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center"><%= "All " + @category.name + " Experiences" %></h1>

<% if logged_in? and current_user.admin? %>
  <h3 class="text-center">
      <%= link_to "Edit this category", edit_category_path(@category), class: "btn btn-warning" %>
  </h3>
<% end %>

<div class="text-center">
  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div class="text-center">
  <%= will_paginate @category_articles %>
</div>