config/routes.rb
Rails.application.routes.draw do
  
  # Homepage
  root 'pages#home'
  
  # User Sessions and Sign Up Page
  get '/signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  # Articles, Users, Categories
  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="text-center">
  <p>
    Copyright &copy; 2016. Made by <%= link_to "Kelsonic", "http://kelsonic.io" %>.
  </p>
</footer>

app/views/layouts/_messages.html.erb
<div class="container-fluid">
  <div class="row text-center">
    <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Dive Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
        <% if current_user %>
          <li><%= link_to "New Article", new_article_path, class: "new-article-nav" %></li>
        <% end %>
      </ul>
      
      <!--Right Navbar-->
      <ul class="nav navbar-nav navbar-right">
        
        <% if !logged_in? %>
          <li><%= link_to 'Sign Up', signup_path %></li>
          <li><%= link_to 'Login', login_path, class: "login" %></li>
          
        <% else %>
        
          <!--Right Dropdown Menu-->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><%= " | Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li><%= link_to 'New Category', new_category_path %></li>
              <% end %>
              <li><%= link_to 'My Profile', user_path(current_user) %></li>
              <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path, method: :delete, class: "logout" %></li>
            </ul>
          </li>
          
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notifications.html.erb
<div class="container-fluid">
  <div class="row text-center">
    <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Dive Blog</title>
  <meta content='<%= logged_in? ? current_user.id : "" %>' name='user-id'/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  
  <%= render 'layouts/notifications' %>
  
  <%= yield %>
    
  <%= render 'layouts/footer' %>
  
  <!--Debugger-->
  <!--<%= debug(params) if Rails.env.development? %>-->

</body>
</html>